### ISSUE TITLE
Why this files isn't the same as you 

### ISSUE THREAD

**Issue by wrossier** [seregazhuk/php-favro-api#6]
Hi,

This file https://github.com/seregazhuk/php-favro-api/blob/master/src/Api/Endpoints/Cards.php isn't the same between us.

I 've made a composer require and in this file i have delete method : 
public function delete($cardId, $everywhere)
    {
        return $this
            ->getHttp()
            ->delete(
                $this->makeRequestUrl($cardId),
                ['everywhere' => $everywhere],
                $this->getHeaders()
            );
    }

But this method isn't corret and i have an error : Strict standards: Declaration of seregazhuk\Favro\Api\Endpoints\Cards::delete() should be compatible with seregazhuk\Favro\Api\Endpoints\CrudEndpoint::delete($itemId) in /Library/WebServer/Documents/sandbox/favro/vendor/seregazhuk/favro-api/src/Api/Endpoints/Cards.php on line 6

I remove and re-install package, i remove composer cache but i'have always this method...

Thanks for helping,
William

**Comment by wrossier** [comment]
ok i need to specify branch : composer require seregazhuk/favro-api:dev-master
Could you please make a version i don't like using dev-master with composer ?
thanks

**Comment by seregazhuk** [comment]
Hi @wrossier. Yes, I've been working on some refactoring. Please update to version `0.2.3`
